name: "Terraform Infra Deploy Pipeline"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Azure Environment for deployment'
        required: true
        default: 'dev'
        options:
        - 'dev'
        - 'prod'

jobs:
  trigger-child-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dev Workflow
        if: github.event_name == 'pull_request' || github.event.inputs.environment == 'dev'
        uses: ./.github/workflows/terraform-child-workflow.yml
        with:
          environment: 'dev'

      - name: Trigger Prod Workflow
        if: github.event_name == 'pull_request' || github.event.inputs.environment == 'prod'
        uses: ./.github/workflows/terraform-child-workflow.yml
        with:
          environment: 'prod'
